repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff-check
        args: ["--config=backend/pyproject.toml"]
      - id: ruff-format
        args: ["--config=backend/pyproject.toml"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: [--pattern, "^release/.*"]
      - id: detect-private-key

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.21
    hooks:
      - id: uv-lock
        args: ["--project", "backend"]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ["--toml-config=backend/pyproject.toml"]
        additional_dependencies:
          [
            flake8-aaa==0.17.*,
            flake8-pyproject==1.2.*,
            wemake-python-styleguide==1.6.*,
          ]

  - repo: https://github.com/softwareone-platform/mpt-tool
    rev: 5.3.0
    hooks:
      - id: check-migrations

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.0.0
    hooks:
      - id: mypy
        args: ["--config-file=backend/pyproject.toml", "backend/swo_playground"]
        pass_filenames: false
        additional_dependencies:
          - mpt-extension-sdk==6.3.*
