owner: sirius
dbup:
  enabled: false
api:
  enabled: true
  serviceAccountName: mpt-extension-usage-reporting-sa
  image: mpt-extension-usage-reporting
  port: 80
  probesEnabled: false
  hosts:
    - customer-api.domain.global
    - extensions-api.domain.global
  http:
    - match:
        - uri:
            prefix: /mpt-extension-usage-reporting-api/
      rewrite:
        uri: /
worker:
  enabled: false
persistence:
  enabled: true
  claimName: mpt-extension-usage-reporting-data
  mountPath: /data
  size: 1Gi
  accessMode: ReadWriteMany
  existingClaim: mpt-extension-usage-reporting-data
env:
  apiFqdn:
    name: MPT_API_BASE_URL
  MpProductsIds:
    name: MPT_PRODUCTS_IDS
  MptBsuDbPath:
    name: MPT_BSU_DB_PATH
    defaultValue: /data/bsu.db
  MpToolStorageType:
    name: MPT_TOOL_STORAGE_TYPE
    defaultValue: local
  SdkExtensionId:
    name: SDK_EXTENSION_ID
  SdkExtensionUrl:
    name: SDK_EXTENSION_URL
  SdkOtelServiceName:
    name: SDK_OTEL_SERVICE_NAME
    defaultValue: Swo.Extension.UsageReporting
  SdkOtelExporters:
    name: SDK_OTEL_EXPORTERS
    defaultValue: otlp
  OtelExporterOtlpEndpoint:
    name: OTEL_EXPORTER_OTLP_ENDPOINT
    defaultValue: http://jaeger:4318
  OtelExporterOtlpProtocol:
    name: OTEL_EXPORTER_OTLP_PROTOCOL
    defaultValue: http/protobuf
secrets:
  MpApiToken:
    name: MPT_API_TOKEN
  SdkExtensionApiKey:
    name: SDK_EXTENSION_API_KEY
cronjobs:
  subscription-usage:
    serviceAccountName: mpt-extension-usage-reporting-sa
    image: mpt-extension-usage-reporting
    schedule: "0 2 * * *"
    command:
      - mpt-billing-subscription-usage
    args:
      - run
