sonar.projectKey=softwareone-platform_mpt-usage-reporting-extension
sonar.organization=softwareone-mpt-github

sonar.language=py

sonar.sources=mpt_usage_reporting_extension
sonar.tests=tests
sonar.inclusions=mpt_usage_reporting_extension/**
sonar.exclusions=tests/**,**/__init__.py

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3
