apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  MPT_API_BASE_URL: {{ .Values.global.MpBaseUrl | quote }}
  MPT_PRODUCTS_IDS: {{ .Values.global.MpProductsIds | quote }}
  MPT_DATABASE_ENTRA_AUTH: {{ .Values.global.MptDatabaseEntraAuth | quote }}
  MPT_TEAMS_NOTIFICATIONS_ENABLED: {{ .Values.global.MptTeamsNotificationsEnabled | quote }}
  MPT_TOOL_STORAGE_TYPE: {{ .Values.global.MpToolStorageType | quote }}
  SDK_EXTENSION_ID: {{ .Values.global.SdkExtensionId | quote }}
  SDK_EXTENSION_URL: {{ .Values.global.SdkExtensionUrl | quote }}
  SDK_OTEL_SERVICE_NAME: {{ .Values.global.SdkOtelServiceName | quote }}
  SDK_OBSERVABILITY_ENABLED: {{ .Values.global.SdkObservabilityEnabled | quote }}
