{{- if and .Values.global.persistence.enabled (not .Values.global.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.global.persistence.claimName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.global.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.global.persistence.size }}
  {{- with .Values.global.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
