apiVersion: v2
name: mpt-usage-reporting-extension
description: Umbrella chart for the MPT usage reporting extension (api + worker subcharts)
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: "6.0.0"

dependencies:
  - name: mpt-usage-reporting-extension-api
    version: 0.1.0
  - name: mpt-usage-reporting-extension-worker
    version: 0.1.0
