# This is a YAML-formatted file.
# Declare variables to be passed into the worker subchart templates.

cliVersion: 2.4.0
owner: turing
git:
  repository: mpt-usage-reporting-extension
image:
  repository: /mpt-usage-reporting-extension
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}

securityContext: {}

accessPolicy: public
accessPolicyAudience: any
# Type of app: test, product, infra
type: product
applicationGroup: pyra-cli

resources: {}

nodeSelector: {}

tolerations: []
